### ISSUE TITLE
[TASK] Add baseUrl to Cypress config

### ISSUE THREAD

**Issue by ericahagle** [rjsturing/rancid-tomatillos#33]
In the `cypress.config.js` file, we can add a baseUrl to the e2e config, so we can call `cy.visit('/')` in test files instead of needing to put in the whole url.

e.g.  in the `cypress.config.js` file:
```
e2e: {
    baseUrl: 'http://localhost:3000/',
}
```

**Comment by rjsturing** [comment]
I've add the baseURL to the config file and added another test. The test seems a little redundant, let me know if you think the 'it' description should be changed or test removed altogether.
