### ISSUE TITLE
[TASK] Write Cypress tests for the detail pages

### ISSUE THREAD

**Issue by ericahagle** [rjsturing/rancid-tomatillos#36]
We'll need to test the functionality and content of the detail pages:
- confirm clicking a movie card takes us to the correct detail page
- confirm that detail page includes appropriate data (poster, title, backdrop, rating, release year, etc)
- confirm that detail page includes back button (and that back button returns user to home page)
- confirm that detail page's url is updated (Router must be implemented first)

Dependencies:
- https://github.com/rjsturing/rancid-tomatillos/issues/15
- https://github.com/rjsturing/rancid-tomatillos/issues/16

**Comment by rjsturing** [comment]
I have a couple working, feel free to check out:
https://github.com/rjsturing/rancid-tomatillos/pull/62
